<x-dashboard-layout>
    <x-slot:heading>Dashboard</x-slot:heading>
        <x-cards/>
        <x-charts/>
        <x-table-data>
            <x-slot:heading>
                Example
            </x-slot:heading>
        </x-table-data>
</x-dashboard-layout>